### ISSUE TITLE
Unable to download dataset

### ISSUE THREAD

**Issue by IncludeMathH** [aycatakmaz/wsvd_dataset_loader#4]
Running the command 
```powershell
bash downloader_script.sh
```
 does not get the required dataset. It seems that this project has been deprecated. Can you provide a new download?
The error information is as follows:
```powershell
[youtube] 00CTJxpyprw: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by aycatakmaz** [comment]
Hi, 
Thank you for your interest in this codebase!

However, this is not my project or my dataset, and unfortunately I am not working on it anymore. I only used it back in the day when I used it for a project.

Best,
Ayca
